# MongoDB 配置
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/monitor_system

# slf4j 配置
logging:
  level:
    com.yizhi: debug

web:
  server:
    nginx-log-path: "F:\\localhost_access_log."
    tomcat-log-path: "F:\\access_"