spring:

# 环境配置
  profiles:
    active: dev

# MongoDB 配置
  data:
    mongodb:
      option:
        min-connection-per-host: 0
        max-connection-per-host: 100
        threads-allowed-to-block-for-connection-multiplier: 5
        server-selection-timeout: 300000
        max-wait-time: 120000
        max-connection-idle-time: 0
        max-connection-life-time: 0
        connect-timeout: 100000
        socket-timeout: 0
        socket-keep-alive: false
        ssl-enabled: false
        ssl-invalid-host-name-allowed: false
        always-use-m-beans: false
        heartbeat-socket-timeout: 20000
        heartbeat-connect-timeout: 20000
        min-heartbeat-frequency: 500
        heartbeat-frequency: 10000
        local-threshold: 15

# 自定义配置
web:
  server:
    nginx-sign: 0
    nginx-name: "Nginx"
    tomcat-sign: 1
    tomcat-name: "Tomcat"

ssh:
  strict-host-key-checking: "no"
  open-channel: "exec"
  charset: "UTF-8"

time:
  common-time-format: "yyyy-MM-dd HH:mm:ss"
  hour-time-format: "yyyy-MM-dd HH:00:00"
  mid-night: "00:00:00"
  nginx-log-time-format: "yyyyMMdd HH:mm:ss"
  nginx-log-time-simple-format: "yyyyMMdd"
  nginx-log-time-format-on-hour: "yyyyMMdd HH:00:00"
  tomcat-log-time-format: "yyyy-MM-dd HH:mm:ss"
  tomcat-log-time-simple-format: "yyyy-MM-dd"
  tomcat-log-time-format-on-hour: "yyyy-MM-dd HH:00:00"

log:
  nginx-log-separator: "_"
  nginx-log-format: ".log"
  tomcat-log-separator: ""
  tomcat-log-format: ".txt"




